#!/bin/sh

SOURCE=$1

if [ $# -ne 1 ]
then
    echo "Error in $0 - Invalid Argument Count"
    echo "Usage: $0 source_path"
    exit
fi

for f in `ls`; do
	if [ -f "$SOURCE/$f" ]; then
		echo copying file $f from $SOURCE to $PWD
		cp "$SOURCE/$f" $PWD
	else
		echo file $f not found in $SOURCE. Skipping...
	fi
done
